---
title: "project II"
output: html_document
---

```{r,echo=FALSE, results='hide',message=FALSE,warning=FALSE}
###loading libraries

suppressWarnings(library(dplyr))
suppressWarnings(library(purrr))
suppressWarnings(library(knitr))
suppressWarnings(library(grid))
suppressWarnings(library(ggplot2))
```

```{r,echo=FALSE, results='hide',message=FALSE,warning=FALSE}
###loading dataset
load("paintings_train.Rdata")
train <- paintings_train
```

```{r,echo=FALSE, results='hide',message=FALSE,warning=FALSE}
###select variables

#Professor's recoding
train <- train %>%
  mutate(shape_recode = ifelse(Shape == "", "Not Available",
                               ifelse(Shape == "ovale", "oval",
                                      ifelse(Shape == "ronde", "round",
                                             ifelse(Shape == "octogon", "octagon", Shape)))))

#recode
train <- train %>%
  mutate(mat_recode = ifelse(mat %in% c("a", "bc", "c","br"), "metal",
                      ifelse(mat %in% c("al", "ar", "m"), "stone",
                      ifelse(mat %in% c("co", "bt", "t","h","ta"), "canvas",
                      ifelse(mat %in% c("p", "ca"), "paper",
                      ifelse(mat %in% c("b"), "wood",
                      ifelse(mat %in% c("o", "e","v","mi","pa","g"), "other",
                      ifelse(mat %in% c("n/a", ""), "uncertain", NA))))))))

train <- train%>%
  mutate(fig_mention = ifelse(nfigures ==0, "no figures", "figures"))

train <- train%>%
  mutate(artist_living_notliving = ifelse(artistliving==0, "not living", "living"))

train <- train%>%
  mutate(history_nohistory = ifelse(history==0, "no history", "history"))

train <- train%>%
  mutate(mytho_nomytho = ifelse(mytho==0, "no mytho", "mytho"))

train <- train%>%
  mutate(finished_nofinished = ifelse(finished==0, "no finished", "finished"))

train <- train%>%
  mutate(LF = ifelse(lrgfont==0, "no LF", "LF"))

#change price into numeric
train$price <- as.numeric(gsub(",","",train$price))

#create a new variable "famous_author"
author_price <- train %>% 
  group_by(authorstandard) %>% 
  summarise(mean_price = mean(price)) %>% 
  ungroup() %>% 
  arrange(desc(mean_price))
train <- train %>% 
  mutate(famous_author = ifelse(authorstandard %in% 
                                  author_price$authorstandard[which(author_price$mean_price >= 3000)],1,0))


#mat_recode
mat_binary <- train %>% 
  group_by(mat_recode) %>% 
  summarise(mean_price = mean(price)) %>% 
  ungroup() %>% 
  arrange(desc(mean_price))
train <- train %>% 
  mutate(mat_bino = ifelse(mat_recode %in% 
                                  mat_binary$mat_recode[which(mat_binary$mean_price >= 800)],1,0))



#Another variable "dealer_author"
train$dealer_author <-0
train <- within(train, dealer_author[dealer == 'R' & origin_author == 'D/FL'] <- 1)
train <- within(train, dealer_author[dealer == 'R' & origin_author == 'S'] <- 1)


#Another variable "dealer_school_pntg"
train$dealer_school <-0
train <- within(train, dealer_school[dealer == 'R' & origin_author == 'D/FL'] <- 1)
train <- within(train, dealer_school[dealer == 'R' & origin_author == 'S'] <- 1)


#Another variable "endbuyer_paired"
train$endbuyer_paired <-0
train <- within(train, endbuyer_paired[endbuyer == 'B' & paired == 0] <- 1)
train <- within(train, endbuyer_paired[endbuyer == 'C' & paired == 0] <- 1)


#Another variable "endbuyer_history"
train$endbuyer_history <-0
train <- within(train, endbuyer_history[endbuyer == 'C' & history == 1] <- 1)



#remove completely descriptive (thus irrelevant) variables
newTrain <- train[,!names(train) %in% c("sale","lot","position","logprice","subject",
                                        "authorstyle","authorstandard","author",
                                        "winningbidder",
                                        "Interm","Height_in","Width_in","Surface_Rect",
                                        "Diam_in","Surface_Rnd","material","mat",
                                        "lands_sc","lands_elem","lands_figs","lands_ment")]

#NA
which(apply(newTrain,2,anyNA) == TRUE)

#remove NA
newTrain <- newTrain[complete.cases(newTrain$Surface),]

#change all character strings to factors
character_vars <- lapply(newTrain, class) == "character"
newTrain[, character_vars] <- lapply(newTrain[, character_vars], as.factor)

#change the level of factor
levels(newTrain$type_intermed)[levels(newTrain$type_intermed)==""] <- "NONE"
levels(newTrain$winningbiddertype)[levels(newTrain$winningbiddertype)==""] <- "NONE"
levels(newTrain$endbuyer)[levels(newTrain$endbuyer)==""] <- "NONE"
levels(newTrain$materialCat)[levels(newTrain$materialCat)==""] <- "NONE"
levels(newTrain$school_pntg)[levels(newTrain$school_pntg)=="S"] <- "OTHER"
levels(newTrain$winningbiddertype)[levels(newTrain$winningbiddertype)=="EBC"] <- "OTHER"
```

```{r,echo=FALSE, results='hide',message=FALSE,warning=FALSE}
###testing dataset
load("paintings_test.Rdata")
test <- paintings_test

#recode
test <- test %>%
  mutate(mat_recode = ifelse(mat %in% c("a", "bc", "c","br"), "metal",
                      ifelse(mat %in% c("al", "ar", "m"), "stone",
                      ifelse(mat %in% c("co", "bt", "t","h","ta"), "canvas",
                      ifelse(mat %in% c("p", "ca"), "paper",
                      ifelse(mat %in% c("b"), "wood",
                      ifelse(mat %in% c("o", "e","v","mi","pa","g"), "other",
                      ifelse(mat %in% c("n/a", ""), "uncertain", NA))))))))

test <- test%>%
  mutate(fig_mention = ifelse(nfigures ==0, "no figures", "figures"))

test <- test%>%
  mutate(artist_living_notliving = ifelse(artistliving==0, "not living", "living"))

test <- test%>%
  mutate(history_nohistory = ifelse(history==0, "no history", "history"))

test <- test%>%
  mutate(mytho_nomytho = ifelse(mytho==0, "no mytho", "mytho"))

test <- test%>%
  mutate(finished_nofinished = ifelse(finished==0, "no finished", "finished"))

test <- test%>%
  mutate(LF = ifelse(lrgfont==0, "no LF", "LF"))

#create a new variable "famous_author"
author_price <- train %>% 
  group_by(authorstandard) %>% 
  summarise(mean_price = mean(price)) %>% 
  ungroup() %>% 
  arrange(desc(mean_price))
test <- test %>% 
  mutate(famous_author = ifelse(authorstandard %in% 
                                  author_price$authorstandard[which(author_price$mean_price >= 3000)],1,0))


#Another variable "dealer_author"
test$dealer_author <-0
test <- within(test, dealer_author[dealer == 'R' & origin_author == 'D/FL'] <- 1)
test <- within(test, dealer_author[dealer == 'R' & origin_author == 'S'] <- 1)


#Another variable "dealer_school_pntg"
test$dealer_school <-0
test <- within(test, dealer_school[dealer == 'R' & origin_author == 'D/FL'] <- 1)
test <- within(test, dealer_school[dealer == 'R' & origin_author == 'S'] <- 1)


#Another variable "endbuyer_paired"
test$endbuyer_paired <-0
test <- within(test, endbuyer_paired[endbuyer == 'B' & paired == 0] <- 1)
test <- within(test, endbuyer_paired[endbuyer == 'C' & paired == 0] <- 1)


#Another variable "endbuyer_paired"
test$endbuyer_history <-0
test <- within(test, endbuyer_history[endbuyer == 'C' & history == 1] <- 1)

#mat_recode
mat_binary <- train %>% 
  group_by(mat_recode) %>% 
  summarise(mean_price = mean(price)) %>% 
  ungroup() %>% 
  arrange(desc(mean_price))
test <- test %>% 
  mutate(mat_bino = ifelse(mat_recode %in% 
                                  mat_binary$mat_recode[which(mat_binary$mean_price >= 800)],1,0))






#Professor's recoding
test <- test %>%
  mutate(shape_recode = ifelse(Shape == "", "Not Available",
                               ifelse(Shape == "ovale", "oval",
                                      ifelse(Shape == "ronde", "round",
                                             ifelse(Shape == "octogon", "octagon", Shape)))))

newTest <- test[,!names(test) %in% c("sale","lot","position","logprice","subject",
                                        "authorstyle","authorstandard","author",
                                        "winningbidder", "price",
                                        "Interm","Height_in","Width_in","Surface_Rect",
                                        "Diam_in","Surface_Rnd","material","mat",
                                        "lands_sc","lands_elem","lands_figs","lands_ment")]

#change all character strings to factors
character_vars <- lapply(newTest, class) == "character"
newTest[, character_vars] <- lapply(newTest[, character_vars], as.factor)

#change the level of factors
levels(newTest$type_intermed)[levels(newTest$type_intermed)==""] <- "NONE"
levels(newTest$winningbiddertype)[levels(newTest$winningbiddertype)==""] <- "NONE"
levels(newTest$endbuyer)[levels(newTest$endbuyer)==""] <- "NONE"
levels(newTest$materialCat)[levels(newTest$materialCat)==""] <- "NONE"
levels(newTest$school_pntg)[levels(newTest$school_pntg)=="A"] <- "OTHER"
levels(newTest$school_pntg)[levels(newTest$school_pntg)=="G"] <- "OTHER"
levels(newTest$winningbiddertype)[levels(newTest$winningbiddertype)=="EBC"] <- "OTHER"
levels(newTest$winningbiddertype)[levels(newTest$winningbiddertype)=="BB"] <- "OTHER"
levels(newTest$winningbiddertype)[levels(newTest$winningbiddertype)=="ED"] <- "OTHER"

#simple method to predict the NA in surface
newTest$Surface[which(is.na(newTest$Surface)==TRUE)] <- mean(newTest$Surface, na.rm = TRUE)
```

```{r,echo=FALSE, results='hide',message=FALSE,warning=FALSE}
###Testing Push
#m <- lm(formula = log(price) ~ dealer + year + school_pntg + diff_origin + 
#        artistliving + winningbiddertype + Surface + engraved + 
#        prevcoll + paired + finished + lrgfont + othgenre +  
#        discauth + winningbiddertype:prevcoll + 
#        Surface:mat_recode + famous_author:Surface, data = newTrain)

#boosting
#m = gbm(log(price) ~ dealer + year + school_pntg + diff_origin + 
#        artistliving + winningbiddertype + Surface + engraved + 
#        prevcoll + paired + finished + lrgfont + othgenre +  
#        discauth + winningbiddertype:prevcoll + 
#        Surface:mat_recode + famous_author:Surface, data = newTrain,
#        distribution = "gaussian", n.trees=5000,interaction.depth = 4)
library(randomForest)
#m= randomForest(log(price) ~ dealer + year + school_pntg + diff_origin + 
#        artistliving + winningbiddertype + Surface + engraved + 
#        prevcoll + paired + finished + lrgfont + othgenre +  
#        discauth+ winningbiddertype:prevcoll + 
#        Surface:mat_recode + famous_author:Surface , data = newTrain,mtry=5,
#        ntree=15000) #1498

#m= randomForest(log(price) ~ dealer + year + school_pntg + diff_origin + 
#        artistliving + winningbiddertype + Surface + engraved + 
#        prevcoll + paired + finished + lrgfont + othgenre +  
#        discauth+ mat_recode + famous_author, data = newTrain,mtry=5,
#        ntree=15000) #1490 increasing the number of trees only improves by 8


#m= randomForest(log(price) ~ dealer + year + school_pntg + diff_origin + 
#        artistliving + winningbiddertype + Surface + engraved + 
#        prevcoll + paired + finished + lrgfont + othgenre +  
#        discauth+ mat_recode + famous_author, data = newTrain,mtry=17,
#        ntree=15000) #to be confirmed at 6:30 1522


#m= randomForest(log(price) ~ dealer + year + school_pntg + diff_origin + 
#        artistliving + winningbiddertype + Surface + engraved + 
#        prevcoll + paired + finished + lrgfont + othgenre +  
#        discauth+ winningbiddertype:prevcoll + 
#        Surface:mat_recode + famous_author:Surface, data = newTrain,mtry=5,
#        ntree=15000) #confrimed at 6:35 add back interaction.1489

#m= randomForest(log(price) ~ dealer + year + school_pntg + diff_origin + 
#        artistliving + winningbiddertype + Surface + engraved + 
#        prevcoll + paired + finished + lrgfont + othgenre +  
#        discauth+ winningbiddertype:prevcoll + 
#        Surface:mat_recode + famous_author:Surface, data = newTrain,mtry=10,
#        ntree=15000) #confirmed at 6:40 1503

#m= randomForest(log(price) ~ dealer + year + school_pntg + diff_origin + 
#        artistliving + winningbiddertype + Surface + engraved + 
#        prevcoll + paired + finished + lrgfont + othgenre +  
#        discauth+ winningbiddertype:prevcoll + 
#        Surface:mat_recode + famous_author:Surface, data = newTrain,mtry=10,
#        ntree=150000)  #1500~~

#m= randomForest(log(price) ~ dealer + year + school_pntg + diff_origin + 
#        artistliving + winningbiddertype + Surface + engraved + 
#        prevcoll + paired + finished + lrgfont + othgenre +  
#        discauth+ winningbiddertype:prevcoll + 
#Surface:mat_recode + famous_author:Surface, data = newTrain,mtry=10,
#        ntree=10000) 
#ln <-lm(formula = log(price) ~ dealer + year + school_pntg + diff_origin + 
#        artistliving + winningbiddertype + Surface + engraved + 
#        prevcoll + paired + finished + lrgfont + othgenre +  
#        discauth + winningbiddertype:prevcoll + 
#        Surface:mat_recode + famous_author:Surface, data = newTrain)

#m= randomForest(log(price) ~ dealer + year + school_pntg + diff_origin + 
#        artistliving + winningbiddertype + Surface + engraved + 
#        prevcoll + paired + finished + lrgfont + othgenre +  
#        discauth+  
#        Surface:mat_recode , data = newTrain,mtry=10, ntree=10000) 

#m= randomForest(log(price) ~ dealer + year + school_pntg + diff_origin + 
#        artistliving + winningbiddertype + Surface + engraved + 
#        prevcoll + paired + finished + lrgfont + othgenre +  
#        discauth+ Surface:mat_recode + famous_author:Surface, data = newTrain,mtry=10, #ntree=10000)  waiting to be verified


#m= randomForest(log(price)~dealer + year + school_pntg + diff_origin + 
#        artistliving + winningbiddertype + Surface + engraved + 
#        prevcoll + paired + finished + lrgfont + othgenre +  
#        discauth + winningbiddertype:prevcoll + 
#        Surface:mat_recode + famous_author:Surface, data = newTrain,mtry=10, ntree=10000) 
  #to be confirmed at 6:0015 0.997 coverage 1503


m= randomForest(log(price)~dealer + year + school_pntg + diff_origin + 
        artistliving + winningbiddertype + Surface + engraved + 
        prevcoll + paired + finished + lrgfont + othgenre +  
        discauth +
        Surface:mat_recode + famous_author:Surface, data = newTrain,mtry=10, ntree=10000) 


```

```{r}
#summary(ln)
```

```{r}
newTest <- newTest %>%
  mutate(price = c(1:dim(newTest)))
newTest <- rbind(newTrain[1, ] , newTest)
newTest <- newTest[-1,]

```

```{r}
pred.interval <- function(model, percentile) {
    
    preds <- predict(model, newdata=newTest,type="response",predict.all=TRUE)
    len <- length(preds$individual[,1])
    err_down <- array(1:3, c(len,1))
    err_up <- array(1:3, c(len,1))
   
    for (i in 1:len){
    err_down[i] <- quantile(preds$individual[i,], (1-percentile)/2 )
    err_up[i] <- quantile(preds$individual[i,], (1+percentile)/2)
    
    }
    error <- array(1:3, c(len,3))
    error[,1] <-exp(preds$aggregate)
    error[,2] <- exp(err_down)
    error[,3] <- exp(err_up)
    return(error)
}
interval <- pred.interval(m,0.997)
```


```{r}
#predictions = as.data.frame(interval)
#colnames(predictions) <- c("fit","lwr","upr")
#save(predictions, file="predict-test.Rdata")
```



```{r,echo=FALSE,message=FALSE,results = 'hide',warning=FALSE}
predictions = as.data.frame(interval)
  #exp(predict(m, newdata=newTest)))
#cbind(predictions,interval[,1],interval[,2])
colnames(predictions) <- c("fit","lwr","ubr")
save(predictions, file="predict-test.Rdata")
#,               interval = "pred",n.trees = 5000
```
